import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/dashboard">Dashboard</Link></li>
            <li><Link href="/blog">Blog</Link></li>
            <li><Link href="/userGithub">User Github</Link></li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  )
}
