import React from 'react'
export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function layout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            {children}
        </div>
    )
}
